export const ROOT = "/"
export const TEAMS = "/teams"
export const PLAYER = "/player"
export const STANDINGS = "/standings"
export const SCHEDULE = "/schedule"
export const USERS = "/users"
export const ALLMATCHES = "/all-matches"
export const MATCH = "/match"
export const LOGIN = "/login"
export const TOURNAMENTS = "/tournament"

